-- Insert all 240 movies organized by 12 moods

-- BUI 1: Lig, Feel-Good & Lekker Kyk
insert into public.movies (title, genre, actors, description, mood_category, mood_number, order_in_mood) values
('The Terminal', 'Drama / Komedie', 'Tom Hanks, Catherine Zeta-Jones', 'Sagte, snaakse storie oor ''n man wat in ''n lughawe vassteek en nuwe vriendskappe bou.', 'Lig, Feel-Good & Lekker Kyk', 1, 1),
('The Intern', 'Drama / Komedie', 'Robert De Niro, Anne Hathaway', '''n Afgetrede man vind nuwe betekenis as intern by ''n jong maatskappy.', 'Lig, Feel-Good & Lekker Kyk', 1, 2),
('Chef', 'Drama / Komedie', 'Jon Favreau, Sofia Vergara', 'Feel-good fliek oor kos, familie en om jou passie terug te vind.', 'Lig, Feel-Good & Lekker Kyk', 1, 3),
('Julie & Julia', 'Drama / Komedie', 'Meryl Streep, Amy Adams', 'Twee vroue verbind oor kos en selfontdekking.', 'Lig, Feel-Good & Lekker Kyk', 1, 4),
('Hitch', 'Romantiese Komedie', 'Will Smith, Eva Mendes', '''n Liefdesafrigter raak self verstrengel in romanse.', 'Lig, Feel-Good & Lekker Kyk', 1, 5),
('Notting Hill', 'Romantiese Komedie', 'Hugh Grant, Julia Roberts', '''n Gewone man raak verlief op ''n filmster.', 'Lig, Feel-Good & Lekker Kyk', 1, 6),
('As Good as It Gets', 'Drama / Komedie', 'Jack Nicholson, Helen Hunt', '''n Moeilike man leer stadig oor liefde en empatie.', 'Lig, Feel-Good & Lekker Kyk', 1, 7),
('The Proposal', 'Romantiese Komedie', 'Sandra Bullock, Ryan Reynolds', '''n Skynverlowing raak meer as net toneelspel.', 'Lig, Feel-Good & Lekker Kyk', 1, 8),
('Mamma Mia!', 'Musiekblyspel / Komedie', 'Meryl Streep, Pierce Brosnan', 'Lig en vrolik met ABBA-liedjies en familiegeheime.', 'Lig, Feel-Good & Lekker Kyk', 1, 9),
('Crazy Rich Asians', 'Romantiese Komedie', 'Constance Wu, Henry Golding', 'Liefde bots met familie-verwachtinge.', 'Lig, Feel-Good & Lekker Kyk', 1, 10),
('Yes Man', 'Komedie', 'Jim Carrey, Zooey Deschanel', '''n Man sê ja vir alles – met verrassende gevolge.', 'Lig, Feel-Good & Lekker Kyk', 1, 11),
('The Bucket List', 'Drama / Komedie', 'Jack Nicholson, Morgan Freeman', 'Twee mans leef hul laaste drome uit.', 'Lig, Feel-Good & Lekker Kyk', 1, 12),
('Paddington', 'Familie / Komedie', 'Ben Whishaw, Hugh Bonneville', '''n Liewe beer bring chaos en warmte.', 'Lig, Feel-Good & Lekker Kyk', 1, 13),
('Eat Pray Love', 'Romantiese Drama', 'Julia Roberts, Javier Bardem', 'Selfontdekking deur reis en liefde.', 'Lig, Feel-Good & Lekker Kyk', 1, 14),
('Little Miss Sunshine', 'Komedie / Drama', 'Steve Carell, Toni Collette', '''n Disfunksionele familie op ''n padtog.', 'Lig, Feel-Good & Lekker Kyk', 1, 15),
('The Hundred-Foot Journey', 'Drama', 'Helen Mirren, Om Puri', 'Kos, kultuur en respek bots.', 'Lig, Feel-Good & Lekker Kyk', 1, 16),
('About Time', 'Romantiese Drama', 'Domhnall Gleeson, Rachel McAdams', 'Liefde, familie en tyd.', 'Lig, Feel-Good & Lekker Kyk', 1, 17),
('Mrs. Doubtfire', 'Familie / Komedie', 'Robin Williams, Sally Field', '''n Pa doen alles om naby sy kinders te bly.', 'Lig, Feel-Good & Lekker Kyk', 1, 18),
('Big', 'Fantasie / Komedie', 'Tom Hanks, Elizabeth Perkins', '''n Seun word oornag ''n volwassene.', 'Lig, Feel-Good & Lekker Kyk', 1, 19),
('The Fundamentals of Caring', 'Drama / Komedie', 'Paul Rudd, Craig Roberts', '''n Padreis verander twee lewens.', 'Lig, Feel-Good & Lekker Kyk', 1, 20);

-- BUI 2: Emosie, Mooi Stories & Lewe
insert into public.movies (title, genre, actors, description, mood_category, mood_number, order_in_mood) values
('Forrest Gump', 'Drama', 'Tom Hanks, Robin Wright', '''n Eenvoudige man beleef ''n buitengewone lewe.', 'Emosie, Mooi Stories & Lewe', 2, 1),
('Good Will Hunting', 'Drama', 'Matt Damon, Robin Williams', 'Selfontdekking deur vriendskap en mentorskap.', 'Emosie, Mooi Stories & Lewe', 2, 2),
('The Shawshank Redemption', 'Drama', 'Tim Robbins, Morgan Freeman', 'Hoop en vriendskap agter tralies.', 'Emosie, Mooi Stories & Lewe', 2, 3),
('A Beautiful Mind', 'Biografiese Drama', 'Russell Crowe, Jennifer Connelly', 'Liefde te midde van geestelike siekte.', 'Emosie, Mooi Stories & Lewe', 2, 4),
('The Green Mile', 'Drama / Fantasie', 'Tom Hanks, Michael Clarke Duncan', 'Menslikheid en genade in ''n tronk.', 'Emosie, Mooi Stories & Lewe', 2, 5),
('The Blind Side', 'Biografiese Drama', 'Sandra Bullock, Quinton Aaron', '''n Familie verander ''n jong man se lewe.', 'Emosie, Mooi Stories & Lewe', 2, 6),
('The Pursuit of Happyness', 'Biografiese Drama', 'Will Smith, Jaden Smith', 'Pa en seun oorleef swaar tye.', 'Emosie, Mooi Stories & Lewe', 2, 7),
('October Sky', 'Biografiese Drama', 'Jake Gyllenhaal, Laura Dern', 'Groot drome uit ''n klein dorpie.', 'Emosie, Mooi Stories & Lewe', 2, 8),
('Rain Man', 'Drama', 'Dustin Hoffman, Tom Cruise', 'Twee broers leer mekaar ken.', 'Emosie, Mooi Stories & Lewe', 2, 9),
('Driving Miss Daisy', 'Drama', 'Jessica Tandy, Morgan Freeman', 'Vriendskap oor jare en kulture.', 'Emosie, Mooi Stories & Lewe', 2, 10),
('Scent of a Woman', 'Drama', 'Al Pacino, Chris O''Donnell', 'Lewe, eer en groei.', 'Emosie, Mooi Stories & Lewe', 2, 11),
('Jerry Maguire', 'Drama / Romantiek', 'Tom Cruise, Renée Zellweger', 'Sport, liefde en menslikheid.', 'Emosie, Mooi Stories & Lewe', 2, 12),
('Field of Dreams', 'Drama / Fantasie', 'Kevin Costner, James Earl Jones', 'Geloof en familie.', 'Emosie, Mooi Stories & Lewe', 2, 13),
('The Notebook', 'Romantiese Drama', 'Ryan Gosling, Rachel McAdams', 'Liefde oor ''n leeftyd.', 'Emosie, Mooi Stories & Lewe', 2, 14),
('Lion', 'Biografiese Drama', 'Dev Patel, Nicole Kidman', '''n Man soek sy verlore familie.', 'Emosie, Mooi Stories & Lewe', 2, 15),
('Million Dollar Baby', 'Sport / Drama', 'Clint Eastwood, Hilary Swank', 'Drome, opoffering en keuses.', 'Emosie, Mooi Stories & Lewe', 2, 16),
('Life of Pi', 'Avontuur / Drama', 'Suraj Sharma, Irrfan Khan', 'Oorlewing en geloof.', 'Emosie, Mooi Stories & Lewe', 2, 17),
('The Reader', 'Romantiese Drama', 'Kate Winslet, Ralph Fiennes', 'Liefde en skuld.', 'Emosie, Mooi Stories & Lewe', 2, 18),
('Manchester by the Sea', 'Drama', 'Casey Affleck, Michelle Williams', 'Rou en herstel.', 'Emosie, Mooi Stories & Lewe', 2, 19),
('A Man Called Otto', 'Drama / Komedie', 'Tom Hanks, Mariana Treviño', '''n Knorrige man ontdek weer menslikheid.', 'Emosie, Mooi Stories & Lewe', 2, 20);

-- BUI 3: Aksie met 'n Storie
insert into public.movies (title, genre, actors, description, mood_category, mood_number, order_in_mood) values
('Die Hard', 'Aksie / Riller', 'Bruce Willis, Alan Rickman', 'Spanning met humor.', 'Aksie met ''n Storie', 3, 1),
('The Fugitive', 'Aksie / Riller', 'Harrison Ford, Tommy Lee Jones', 'Onskuldige man op die vlug.', 'Aksie met ''n Storie', 3, 2),
('First Blood', 'Aksie / Drama', 'Sylvester Stallone', 'Rambo met storie en emosie.', 'Aksie met ''n Storie', 3, 3),
('Jack Reacher', 'Aksie / Riller', 'Tom Cruise', 'Rustige, slim aksie.', 'Aksie met ''n Storie', 3, 4),
('Ocean''s Eleven', 'Aksie / Misdaad', 'George Clooney, Brad Pitt', 'Slim rooftog met styl.', 'Aksie met ''n Storie', 3, 5),
('Gran Torino', 'Drama', 'Clint Eastwood', 'Taai man met ''n sagte kern.', 'Aksie met ''n Storie', 3, 6),
('The Equalizer', 'Aksie / Riller', 'Denzel Washington', 'Regverdigheid met krag.', 'Aksie met ''n Storie', 3, 7),
('Patriot Games', 'Aksie / Riller', 'Harrison Ford', 'Gesin en gevaar.', 'Aksie met ''n Storie', 3, 8),
('Enemy of the State', 'Aksie / Riller', 'Will Smith, Gene Hackman', 'Tegnologie en spanning.', 'Aksie met ''n Storie', 3, 9),
('Argo', 'Riller / Drama', 'Ben Affleck', 'Ware reddingsverhaal.', 'Aksie met ''n Storie', 3, 10),
('Bridge of Spies', 'Historiese Drama', 'Tom Hanks', 'Onderhandeling bo geweld.', 'Aksie met ''n Storie', 3, 11),
('The Italian Job', 'Aksie / Avontuur', 'Mark Wahlberg', 'Slim wraakplan.', 'Aksie met ''n Storie', 3, 12),
('Shooter', 'Aksie / Riller', 'Mark Wahlberg', 'Samenzwering en oorlewing.', 'Aksie met ''n Storie', 3, 13),
('Taken', 'Aksie / Riller', 'Liam Neeson', 'Pa doen alles vir sy kind.', 'Aksie met ''n Storie', 3, 14),
('Blood Diamond', 'Avontuur / Riller', 'Leonardo DiCaprio', 'Konflik en menslikheid.', 'Aksie met ''n Storie', 3, 15),
('The Bourne Identity', 'Aksie / Riller', 'Matt Damon', 'Geheueverlies en geheime.', 'Aksie met ''n Storie', 3, 16),
('Edge of Tomorrow', 'Sci-Fi / Aksie', 'Tom Cruise, Emily Blunt', 'Aksie met slim konsep.', 'Aksie met ''n Storie', 3, 17),
('Air Force One', 'Aksie / Riller', 'Harrison Ford', 'President in gevaar.', 'Aksie met ''n Storie', 3, 18),
('The Rock', 'Aksie / Riller', 'Sean Connery, Nicolas Cage', 'Klassieke spanning.', 'Aksie met ''n Storie', 3, 19),
('Gladiator', 'Historiese Drama', 'Russell Crowe', 'Eer, wraak en nalatenskap.', 'Aksie met ''n Storie', 3, 20);

-- BUI 4: Sport, Onderdogs & Motivering
insert into public.movies (title, genre, actors, description, mood_category, mood_number, order_in_mood) values
('The Karate Kid', 'Sport / Drama', 'Ralph Macchio, Pat Morita', 'Dissipline, mentorskap en selfvertroue.', 'Sport, Onderdogs & Motivering', 4, 1),
('Rocky', 'Sport / Drama', 'Sylvester Stallone, Talia Shire', 'Klassieke underdog-verhaal vol hart.', 'Sport, Onderdogs & Motivering', 4, 2),
('Creed', 'Sport / Drama', 'Michael B. Jordan, Sylvester Stallone', 'Nalatenskap en mentorskap in boks.', 'Sport, Onderdogs & Motivering', 4, 3),
('Rocky II', 'Sport / Drama', 'Sylvester Stallone, Talia Shire', 'Volharding ná die groot kans.', 'Sport, Onderdogs & Motivering', 4, 4),
('Creed II', 'Sport / Drama', 'Michael B. Jordan, Dolph Lundgren', 'Familie en identiteit.', 'Sport, Onderdogs & Motivering', 4, 5),
('Remember the Titans', 'Sport / Drama', 'Denzel Washington, Will Patton', 'Spanwerk en respek.', 'Sport, Onderdogs & Motivering', 4, 6),
('Rudy', 'Sport / Drama', 'Sean Astin, Jon Favreau', 'Nooit ophou droom nie.', 'Sport, Onderdogs & Motivering', 4, 7),
('The Rookie', 'Sport / Drama', 'Dennis Quaid', 'Dit is nooit te laat nie.', 'Sport, Onderdogs & Motivering', 4, 8),
('Million Dollar Baby', 'Sport / Drama', 'Clint Eastwood, Hilary Swank', 'Drome en opoffering.', 'Sport, Onderdogs & Motivering', 4, 9),
('Invictus', 'Sport / Historiese Drama', 'Morgan Freeman, Matt Damon', 'Rugby, leierskap en versoening.', 'Sport, Onderdogs & Motivering', 4, 10),
('Chariots of Fire', 'Historiese Sportdrama', 'Ben Cross, Ian Charleson', 'Geloof en eer.', 'Sport, Onderdogs & Motivering', 4, 11),
('The Blind Side', 'Biografiese Drama', 'Sandra Bullock, Quinton Aaron', 'Omgee verander lewens.', 'Sport, Onderdogs & Motivering', 4, 12),
('Coach Carter', 'Sport / Drama', 'Samuel L. Jackson', 'Dissipline bo oorwinning.', 'Sport, Onderdogs & Motivering', 4, 13),
('Moneyball', 'Sport / Drama', 'Brad Pitt, Jonah Hill', 'Slim dink verander sport.', 'Sport, Onderdogs & Motivering', 4, 14),
('Rush', 'Sport / Biografiese Drama', 'Chris Hemsworth, Daniel Brühl', 'Mededinging en respek.', 'Sport, Onderdogs & Motivering', 4, 15),
('Seabiscuit', 'Sport / Drama', 'Tobey Maguire, Jeff Bridges', '''n Perd en hoop.', 'Sport, Onderdogs & Motivering', 4, 16),
('Warrior', 'Sport / Drama', 'Tom Hardy, Joel Edgerton', 'Familie en vergifnis.', 'Sport, Onderdogs & Motivering', 4, 17),
('McFarland, USA', 'Sport / Drama', 'Kevin Costner', 'Jongmense en geleenthede.', 'Sport, Onderdogs & Motivering', 4, 18),
('Southpaw', 'Sport / Drama', 'Jake Gyllenhaal', 'Terugveg na verlies.', 'Sport, Onderdogs & Motivering', 4, 19),
('The Way Back', 'Sport / Drama', 'Ben Affleck', 'Genesing deur sport.', 'Sport, Onderdogs & Motivering', 4, 20);

-- Continue with remaining moods...
-- BUI 5: Romanties & Klassiek
insert into public.movies (title, genre, actors, description, mood_category, mood_number, order_in_mood) values
('Sleepless in Seattle', 'Romantiese Komedie', 'Tom Hanks, Meg Ryan', 'Klassieke romantiese komedie.', 'Romanties & Klassiek', 5, 1),
('Notting Hill', 'Romantiese Komedie', 'Hugh Grant, Julia Roberts', '''n Gewone man raak verlief op ''n filmster.', 'Romanties & Klassiek', 5, 2),
('The Notebook', 'Romantiese Drama', 'Ryan Gosling, Rachel McAdams', 'Liefde oor ''n leeftyd.', 'Romanties & Klassiek', 5, 3),
('As Good as It Gets', 'Drama / Komedie', 'Jack Nicholson, Helen Hunt', '''n Moeilike man leer stadig oor liefde en empatie.', 'Romanties & Klassiek', 5, 4),
('Jerry Maguire', 'Drama / Romantiek', 'Tom Cruise, Renée Zellweger', 'Sport, liefde en menslikheid.', 'Romanties & Klassiek', 5, 5),
('The Bodyguard', 'Romantiese Riller', 'Kevin Costner, Whitney Houston', 'Beskermende liefde.', 'Romanties & Klassiek', 5, 6),
('Pretty Woman', 'Romantiese Komedie', 'Richard Gere, Julia Roberts', 'Moderne sprokiesverhaal.', 'Romanties & Klassiek', 5, 7),
('When Harry Met Sally', 'Romantiese Komedie', 'Billy Crystal, Meg Ryan', 'Vriendskap en liefde.', 'Romanties & Klassiek', 5, 8),
('You''ve Got Mail', 'Romantiese Komedie', 'Tom Hanks, Meg Ryan', 'Aanlyn liefde voor sosiale media.', 'Romanties & Klassiek', 5, 9),
('Bridges of Madison County', 'Romantiese Drama', 'Clint Eastwood, Meryl Streep', 'Kort maar onvergeetlike liefde.', 'Romanties & Klassiek', 5, 10),
('Ghost', 'Romantiese Fantasie', 'Patrick Swayze, Demi Moore', 'Liefde oor die dood heen.', 'Romanties & Klassiek', 5, 11),
('Sense and Sensibility', 'Romantiese Drama', 'Emma Thompson, Kate Winslet', 'Jane Austen se klassiek.', 'Romanties & Klassiek', 5, 12),
('Out of Africa', 'Romantiese Drama', 'Robert Redford, Meryl Streep', 'Epies en romanties.', 'Romanties & Klassiek', 5, 13),
('The English Patient', 'Romantiese Drama', 'Ralph Fiennes, Kristin Scott Thomas', 'Intense, komplekse liefde.', 'Romanties & Klassiek', 5, 14),
('Love Actually', 'Romantiese Komedie', 'Hugh Grant, Emma Thompson', 'Veelvoudige liefdesverhale.', 'Romanties & Klassiek', 5, 15),
('Four Weddings and a Funeral', 'Romantiese Komedie', 'Hugh Grant', 'Britse charme en romanse.', 'Romanties & Klassiek', 5, 16),
('The Proposal', 'Romantiese Komedie', 'Sandra Bullock, Ryan Reynolds', '''n Skynverlowing raak meer as net toneelspel.', 'Romanties & Klassiek', 5, 17),
('An Affair to Remember', 'Romantiese Drama', 'Cary Grant, Deborah Kerr', 'Klassieke Hollywood-romanse.', 'Romanties & Klassiek', 5, 18),
('Roman Holiday', 'Romantiese Komedie', 'Audrey Hepburn, Gregory Peck', 'Tydlose elegansie.', 'Romanties & Klassiek', 5, 19),
('Dirty Dancing', 'Romantiese Drama', 'Patrick Swayze, Jennifer Grey', 'Dans en somer-romanse.', 'Romanties & Klassiek', 5, 20);

-- BUI 6: Ou Gunstelinge (60s-80s Klassiek)
insert into public.movies (title, genre, actors, description, mood_category, mood_number, order_in_mood) values
('Casablanca', 'Romantiese Drama', 'Humphrey Bogart, Ingrid Bergman', 'Klassieke liefde en opoffering.', 'Ou Gunstelinge (60s-80s Klassiek)', 6, 1),
('The Sound of Music', 'Musiekblyspel / Drama', 'Julie Andrews', 'Familie, musiek en hoop.', 'Ou Gunstelinge (60s-80s Klassiek)', 6, 2),
('Mary Poppins', 'Familie / Fantasie', 'Julie Andrews, Dick Van Dyke', 'Tydlose familiepret.', 'Ou Gunstelinge (60s-80s Klassiek)', 6, 3),
('To Kill a Mockingbird', 'Drama', 'Gregory Peck', 'Geregtigheid en menslikheid.', 'Ou Gunstelinge (60s-80s Klassiek)', 6, 4),
('Ben-Hur', 'Historiese Drama', 'Charlton Heston', 'Eer en geloof.', 'Ou Gunstelinge (60s-80s Klassiek)', 6, 5),
('The Great Escape', 'Avontuur / Drama', 'Steve McQueen', 'Klassieke spanning.', 'Ou Gunstelinge (60s-80s Klassiek)', 6, 6),
('Breakfast at Tiffany''s', 'Romantiese Komedie', 'Audrey Hepburn', 'Styl en sagtheid.', 'Ou Gunstelinge (60s-80s Klassiek)', 6, 7),
('Singin'' in the Rain', 'Musiekblyspel', 'Gene Kelly', 'Pure vreugde.', 'Ou Gunstelinge (60s-80s Klassiek)', 6, 8),
('Doctor Zhivago', 'Romantiese Drama', 'Omar Sharif', 'Liefde teen geskiedenis.', 'Ou Gunstelinge (60s-80s Klassiek)', 6, 9),
('The African Queen', 'Avontuur / Romantiek', 'Humphrey Bogart, Katharine Hepburn', 'Humor en romanse.', 'Ou Gunstelinge (60s-80s Klassiek)', 6, 10),
('Rocky', 'Sport / Drama', 'Sylvester Stallone', 'Underdog-klassieker.', 'Ou Gunstelinge (60s-80s Klassiek)', 6, 11),
('E.T. the Extra-Terrestrial', 'Fantasie / Drama', 'Henry Thomas', 'Onskuld en vriendskap.', 'Ou Gunstelinge (60s-80s Klassiek)', 6, 12),
('Jaws', 'Riller / Avontuur', 'Roy Scheider', 'Spanning sonder gore.', 'Ou Gunstelinge (60s-80s Klassiek)', 6, 13),
('Grease', 'Musiekblyspel', 'John Travolta, Olivia Newton-John', 'Lig en nostalgies.', 'Ou Gunstelinge (60s-80s Klassiek)', 6, 14),
('The Godfather', 'Misdaad / Drama', 'Marlon Brando, Al Pacino', 'Familie en mag.', 'Ou Gunstelinge (60s-80s Klassiek)', 6, 15),
('Chinatown', 'Riller', 'Jack Nicholson', 'Slim misterie.', 'Ou Gunstelinge (60s-80s Klassiek)', 6, 16),
('Star Wars: A New Hope', 'Sci-Fi / Avontuur', 'Mark Hamill, Harrison Ford', 'Heldereise.', 'Ou Gunstelinge (60s-80s Klassiek)', 6, 17),
('Close Encounters of the Third Kind', 'Sci-Fi / Drama', 'Richard Dreyfuss', 'Verwondering.', 'Ou Gunstelinge (60s-80s Klassiek)', 6, 18),
('The Sting', 'Misdaad / Komedie', 'Paul Newman, Robert Redford', 'Slim planne.', 'Ou Gunstelinge (60s-80s Klassiek)', 6, 19),
('Raiders of the Lost Ark', 'Avontuur', 'Harrison Ford', 'Klassieke avontuur.', 'Ou Gunstelinge (60s-80s Klassiek)', 6, 20);

-- BUI 7: Slim Rillers & Mysteries (Nie Skrikkerig Nie)
insert into public.movies (title, genre, actors, description, mood_category, mood_number, order_in_mood) values
('The Fugitive', 'Riller', 'Harrison Ford', 'Onskuldige man op die vlug.', 'Slim Rillers & Mysteries', 7, 1),
('Argo', 'Riller / Drama', 'Ben Affleck', 'Ware reddingsverhaal.', 'Slim Rillers & Mysteries', 7, 2),
('Bridge of Spies', 'Historiese Drama', 'Tom Hanks', 'Onderhandeling bo geweld.', 'Slim Rillers & Mysteries', 7, 3),
('The Imitation Game', 'Biografiese Drama', 'Benedict Cumberbatch', 'Kode-breking en offer.', 'Slim Rillers & Mysteries', 7, 4),
('Spotlight', 'Drama', 'Mark Ruffalo', 'Waarheidsoeke.', 'Slim Rillers & Mysteries', 7, 5),
('All the President''s Men', 'Historiese Riller', 'Robert Redford', 'Watergate-ondersoek.', 'Slim Rillers & Mysteries', 7, 6),
('The Post', 'Drama', 'Meryl Streep, Tom Hanks', 'Joernalistiek en moed.', 'Slim Rillers & Mysteries', 7, 7),
('Tinker Tailor Soldier Spy', 'Spioenasie / Drama', 'Gary Oldman', 'Koue Oorlog-intriges.', 'Slim Rillers & Mysteries', 7, 8),
('A Few Good Men', 'Drama', 'Tom Cruise, Jack Nicholson', 'Hofkamer-spanning.', 'Slim Rillers & Mysteries', 7, 9),
('Michael Clayton', 'Riller', 'George Clooney', 'Korporatiewe geheime.', 'Slim Rillers & Mysteries', 7, 10),
('The Conversation', 'Riller', 'Gene Hackman', 'Afluister en skuld.', 'Slim Rillers & Mysteries', 7, 11),
('The Pelican Brief', 'Riller', 'Julia Roberts, Denzel Washington', 'Samenzwering en gevaar.', 'Slim Rillers & Mysteries', 7, 12),
('Zodiac', 'Misterie', 'Jake Gyllenhaal', 'Ware moordenaar-soektog.', 'Slim Rillers & Mysteries', 7, 13),
('Primal Fear', 'Riller', 'Richard Gere, Edward Norton', 'Hofkamer-draaie.', 'Slim Rillers & Mysteries', 7, 14),
('The Insider', 'Drama', 'Russell Crowe, Al Pacino', 'Waarheid en opoffering.', 'Slim Rillers & Mysteries', 7, 15),
('Enemy of the State', 'Riller', 'Will Smith', 'Tegnologie en spanning.', 'Slim Rillers & Mysteries', 7, 16),
('No Way Out', 'Riller', 'Kevin Costner', 'Geheime en verraad.', 'Slim Rillers & Mysteries', 7, 17),
('Runaway Jury', 'Drama', 'John Cusack', 'Jury-manipulasie.', 'Slim Rillers & Mysteries', 7, 18),
('The Constant Gardener', 'Riller / Drama', 'Ralph Fiennes', 'Samenzwering in Afrika.', 'Slim Rillers & Mysteries', 7, 19),
('Gone Baby Gone', 'Misterie', 'Casey Affleck', 'Kind verdwyn.', 'Slim Rillers & Mysteries', 7, 20);

-- BUI 8: "Perfek vir Ma" Ultra-Sag (Geen Spanning)
insert into public.movies (title, genre, actors, description, mood_category, mood_number, order_in_mood) values
('Driving Miss Daisy', 'Drama', 'Jessica Tandy, Morgan Freeman', 'Vriendskap oor jare en kulture.', 'Perfek vir Ma - Ultra-Sag', 8, 1),
('The Best Exotic Marigold Hotel', 'Drama / Komedie', 'Judi Dench', 'Aftrede en nuwe avonture.', 'Perfek vir Ma - Ultra-Sag', 8, 2),
('Ladies in Lavender', 'Drama', 'Judi Dench, Maggie Smith', 'Twee susters en ''n vreemdeling.', 'Perfek vir Ma - Ultra-Sag', 8, 3),
('Calendar Girls', 'Komedie / Drama', 'Helen Mirren', 'Vroue maak ''n verskil.', 'Perfek vir Ma - Ultra-Sag', 8, 4),
('Finding Neverland', 'Drama', 'Johnny Depp', 'Peter Pan se oorsprong.', 'Perfek vir Ma - Ultra-Sag', 8, 5),
('The Straight Story', 'Drama', 'Richard Farnsworth', 'Eenvoudige, mooi reis.', 'Perfek vir Ma - Ultra-Sag', 8, 6),
('Philomena', 'Drama', 'Judi Dench', 'Soektog na ''n seun.', 'Perfek vir Ma - Ultra-Sag', 8, 7),
('Our Souls at Night', 'Romantiese Drama', 'Robert Redford, Jane Fonda', 'Laaste kans op gelukkigheid.', 'Perfek vir Ma - Ultra-Sag', 8, 8),
('A Good Year', 'Romantiese Drama', 'Russell Crowe', 'Wyn en lewe.', 'Perfek vir Ma - Ultra-Sag', 8, 9),
('Mrs. Harris Goes to Paris', 'Drama / Komedie', 'Lesley Manville', 'Drome en elegansie.', 'Perfek vir Ma - Ultra-Sag', 8, 10),
('The Guernsey Literary and Potato Peel Pie Society', 'Romantiese Drama', 'Lily James', 'Boeke en gemeenskap.', 'Perfek vir Ma - Ultra-Sag', 8, 11),
('The Lunchbox', 'Drama', 'Irrfan Khan', 'Verbinding deur kos.', 'Perfek vir Ma - Ultra-Sag', 8, 12),
('Still Alice', 'Drama', 'Julianne Moore', 'Waardigheid te midde van siekte.', 'Perfek vir Ma - Ultra-Sag', 8, 13),
('Brooklyn', 'Romantiese Drama', 'Saoirse Ronan', 'Immigrasie en liefde.', 'Perfek vir Ma - Ultra-Sag', 8, 14),
('Amélie', 'Romantiese Komedie', 'Audrey Tautou', 'Franse charme.', 'Perfek vir Ma - Ultra-Sag', 8, 15),
('Sense and Sensibility', 'Romantiese Drama', 'Emma Thompson', 'Jane Austen se klassiek.', 'Perfek vir Ma - Ultra-Sag', 8, 16),
('Chocolat', 'Drama / Romantiek', 'Juliette Binoche', 'Sjokolade en transformasie.', 'Perfek vir Ma - Ultra-Sag', 8, 17),
('The Remains of the Day', 'Drama', 'Anthony Hopkins', 'Stille emosie.', 'Perfek vir Ma - Ultra-Sag', 8, 18),
('August Rush', 'Drama', 'Freddie Highmore', 'Musiek verbind.', 'Perfek vir Ma - Ultra-Sag', 8, 19),
('The Music Man', 'Musiekblyspel', 'Robert Preston', 'Klassieke musiekblyspel.', 'Perfek vir Ma - Ultra-Sag', 8, 20);

-- BUI 9: Bruce Willis / Stallone / Harrison Ford Only
insert into public.movies (title, genre, actors, description, mood_category, mood_number, order_in_mood) values
('Die Hard', 'Aksie', 'Bruce Willis', 'Klassieke aksie-klassieker.', 'Bruce Willis / Stallone / Harrison Ford Only', 9, 1),
('Die Hard 2', 'Aksie', 'Bruce Willis', 'Lughawe-chaos.', 'Bruce Willis / Stallone / Harrison Ford Only', 9, 2),
('Die Hard with a Vengeance', 'Aksie', 'Bruce Willis', 'New York-bomme.', 'Bruce Willis / Stallone / Harrison Ford Only', 9, 3),
('Rocky', 'Sport / Drama', 'Sylvester Stallone', 'Underdog-klassieker.', 'Bruce Willis / Stallone / Harrison Ford Only', 9, 4),
('Rocky II', 'Sport / Drama', 'Sylvester Stallone', 'Terugkeer na die ring.', 'Bruce Willis / Stallone / Harrison Ford Only', 9, 5),
('Rocky III', 'Sport / Drama', 'Sylvester Stallone', 'Nuwe uitdagings.', 'Bruce Willis / Stallone / Harrison Ford Only', 9, 6),
('First Blood', 'Aksie / Drama', 'Sylvester Stallone', 'Rambo se oorsprong.', 'Bruce Willis / Stallone / Harrison Ford Only', 9, 7),
('Rambo: First Blood Part II', 'Aksie', 'Sylvester Stallone', 'Rambo in aksie.', 'Bruce Willis / Stallone / Harrison Ford Only', 9, 8),
('The Fugitive', 'Riller', 'Harrison Ford', 'Op die vlug.', 'Bruce Willis / Stallone / Harrison Ford Only', 9, 9),
('Air Force One', 'Aksie', 'Harrison Ford', 'President in gevaar.', 'Bruce Willis / Stallone / Harrison Ford Only', 9, 10),
('Patriot Games', 'Aksie', 'Harrison Ford', 'Jack Ryan.', 'Bruce Willis / Stallone / Harrison Ford Only', 9, 11),
('Clear and Present Danger', 'Aksie', 'Harrison Ford', 'Jack Ryan se avonture.', 'Bruce Willis / Stallone / Harrison Ford Only', 9, 12),
('Witness', 'Drama / Riller', 'Harrison Ford', 'Amish-gemeenskap.', 'Bruce Willis / Stallone / Harrison Ford Only', 9, 13),
('Presumed Innocent', 'Drama', 'Harrison Ford', 'Moord en skuld.', 'Bruce Willis / Stallone / Harrison Ford Only', 9, 14),
('Blade Runner', 'Sci-Fi', 'Harrison Ford', 'Futuristiese noir.', 'Bruce Willis / Stallone / Harrison Ford Only', 9, 15),
('Indiana Jones and the Last Crusade', 'Avontuur', 'Harrison Ford', 'Heilige Graal.', 'Bruce Willis / Stallone / Harrison Ford Only', 9, 16),
('Indiana Jones and the Raiders of the Lost Ark', 'Avontuur', 'Harrison Ford', 'Ark van die Verbond.', 'Bruce Willis / Stallone / Harrison Ford Only', 9, 17),
('Unbreakable', 'Drama / Riller', 'Bruce Willis', 'Superheld-oorsprong.', 'Bruce Willis / Stallone / Harrison Ford Only', 9, 18),
('The Expendables', 'Aksie', 'Stallone, Willis', 'Legende-spanne.', 'Bruce Willis / Stallone / Harrison Ford Only', 9, 19),
('Cop Land', 'Drama', 'Sylvester Stallone', 'Stallone dramatisch.', 'Bruce Willis / Stallone / Harrison Ford Only', 9, 20);

-- BUI 10: Ware Verhale & Biografiese Flieks
insert into public.movies (title, genre, actors, description, mood_category, mood_number, order_in_mood) values
('Schindler''s List', 'Historiese Drama', 'Liam Neeson', 'Redding tydens Holocaust.', 'Ware Verhale & Biografiese Flieks', 10, 1),
('The King''s Speech', 'Biografiese Drama', 'Colin Firth', 'Koning oorkom stotter.', 'Ware Verhale & Biografiese Flieks', 10, 2),
('Hidden Figures', 'Biografiese Drama', 'Taraji P. Henson', 'NASA-vroue.', 'Ware Verhale & Biografiese Flieks', 10, 3),
('The Social Network', 'Biografiese Drama', 'Jesse Eisenberg', 'Facebook se oorsprong.', 'Ware Verhale & Biografiese Flieks', 10, 4),
('Apollo 13', 'Historiese Drama', 'Tom Hanks', 'Ruimte-ramp.', 'Ware Verhale & Biografiese Flieks', 10, 5),
('Erin Brockovich', 'Biografiese Drama', 'Julia Roberts', 'Regverdigheid vir gewone mense.', 'Ware Verhale & Biografiese Flieks', 10, 6),
('Walk the Line', 'Biografiese Drama', 'Joaquin Phoenix', 'Johnny Cash.', 'Ware Verhale & Biografiese Flieks', 10, 7),
('Ray', 'Biografiese Drama', 'Jamie Foxx', 'Ray Charles.', 'Ware Verhale & Biografiese Flieks', 10, 8),
('The Theory of Everything', 'Biografiese Drama', 'Eddie Redmayne', 'Stephen Hawking.', 'Ware Verhale & Biografiese Flieks', 10, 9),
('A Beautiful Day in the Neighborhood', 'Biografiese Drama', 'Tom Hanks', 'Mr. Rogers.', 'Ware Verhale & Biografiese Flieks', 10, 10),
('The Blind Side', 'Biografiese Drama', 'Sandra Bullock', 'Omgee verander lewens.', 'Ware Verhale & Biografiese Flieks', 10, 11),
('The Pursuit of Happyness', 'Biografiese Drama', 'Will Smith', 'Pa en seun oorleef swaar tye.', 'Ware Verhale & Biografiese Flieks', 10, 12),
('Lion', 'Biografiese Drama', 'Dev Patel', '''n Man soek sy verlore familie.', 'Ware Verhale & Biografiese Flieks', 10, 13),
('Hotel Rwanda', 'Historiese Drama', 'Don Cheadle', 'Redding tydens volksmoord.', 'Ware Verhale & Biografiese Flieks', 10, 14),
('Gandhi', 'Biografiese Drama', 'Ben Kingsley', 'Vreedsame verset.', 'Ware Verhale & Biografiese Flieks', 10, 15),
('Invictus', 'Biografiese Drama', 'Morgan Freeman', 'Rugby en versoening.', 'Ware Verhale & Biografiese Flieks', 10, 16),
('Julie & Julia', 'Biografiese Drama', 'Meryl Streep', 'Kos en inspirasie.', 'Ware Verhale & Biografiese Flieks', 10, 17),
('Sully', 'Biografiese Drama', 'Tom Hanks', 'Hudson River-landing.', 'Ware Verhale & Biografiese Flieks', 10, 18),
('The Pianist', 'Historiese Drama', 'Adrien Brody', 'Oorlewing tydens WO2.', 'Ware Verhale & Biografiese Flieks', 10, 19),
('Darkest Hour', 'Biografiese Drama', 'Gary Oldman', 'Churchill se leierskap.', 'Ware Verhale & Biografiese Flieks', 10, 20);

-- BUI 11: Musiek & Dans (Lig, Vrolik & Klassiek)
insert into public.movies (title, genre, actors, description, mood_category, mood_number, order_in_mood) values
('Singin'' in the Rain', 'Musiekblyspel', 'Gene Kelly', 'Pure vreugde en dansklassiek.', 'Musiek & Dans', 11, 1),
('The Sound of Music', 'Musiekblyspel / Drama', 'Julie Andrews', 'Familie, hoop en liedjies.', 'Musiek & Dans', 11, 2),
('Grease', 'Musiekblyspel', 'John Travolta, Olivia Newton-John', 'Nostalgies en lig.', 'Musiek & Dans', 11, 3),
('West Side Story', 'Musiekblyspel / Drama', 'Natalie Wood', 'Liefde en konflik deur musiek.', 'Musiek & Dans', 11, 4),
('Mamma Mia!', 'Musiekblyspel / Komedie', 'Meryl Streep', 'ABBA, son en familie.', 'Musiek & Dans', 11, 5),
('Chicago', 'Musiekblyspel / Drama', 'Renée Zellweger', 'Stylvolle sang en dans.', 'Musiek & Dans', 11, 6),
('Fiddler on the Roof', 'Musiekblyspel / Drama', 'Topol', 'Tradisie en verandering.', 'Musiek & Dans', 11, 7),
('La La Land', 'Musiekblyspel / Romantiek', 'Ryan Gosling, Emma Stone', 'Drome en liefde.', 'Musiek & Dans', 11, 8),
('The King and I', 'Musiekblyspel', 'Yul Brynner, Deborah Kerr', 'Klassieke verhoogverhaal.', 'Musiek & Dans', 11, 9),
('My Fair Lady', 'Musiekblyspel', 'Audrey Hepburn', 'Styl, taal en romanse.', 'Musiek & Dans', 11, 10),
('Cabaret', 'Musiekblyspel / Drama', 'Liza Minnelli', 'Donkerder, maar meesterlik.', 'Musiek & Dans', 11, 11),
('An American in Paris', 'Musiekblyspel', 'Gene Kelly', 'Dans en romanse.', 'Musiek & Dans', 11, 12),
('White Christmas', 'Musiekblyspel', 'Bing Crosby', 'Warm en feestelik.', 'Musiek & Dans', 11, 13),
('Funny Girl', 'Musiekblyspel', 'Barbra Streisand', 'Talent en liefde.', 'Musiek & Dans', 11, 14),
('A Star Is Born', 'Musiek / Drama', 'Barbra Streisand', 'Roem en opoffering.', 'Musiek & Dans', 11, 15),
('Hairspray', 'Musiekblyspel / Komedie', 'John Travolta', 'Energie en pret.', 'Musiek & Dans', 11, 16),
('Billy Elliot', 'Drama / Dans', 'Jamie Bell', 'Dans teen alle verwagtinge.', 'Musiek & Dans', 11, 17),
('The Commitments', 'Musiek / Komedie', 'Robert Arkins', 'Ierse soul en humor.', 'Musiek & Dans', 11, 18),
('Flashdance', 'Dans / Drama', 'Jennifer Beals', 'Drome en deursettingsvermoë.', 'Musiek & Dans', 11, 19),
('Footloose', 'Dans / Drama', 'Kevin Bacon', 'Dans as bevryding.', 'Musiek & Dans', 11, 20);

-- BUI 12: Ou Speurverhale (Agatha Christie-styl)
insert into public.movies (title, genre, actors, description, mood_category, mood_number, order_in_mood) values
('Murder on the Orient Express', 'Misterie', 'Albert Finney', 'Klassieke treinmoord.', 'Ou Speurverhale (Agatha Christie-styl)', 12, 1),
('Death on the Nile', 'Misterie', 'Peter Ustinov', 'Moord op ''n luukse boot.', 'Ou Speurverhale (Agatha Christie-styl)', 12, 2),
('Evil Under the Sun', 'Misterie', 'Peter Ustinov', 'Son, see en geheime.', 'Ou Speurverhale (Agatha Christie-styl)', 12, 3),
('Witness for the Prosecution', 'Hof / Misterie', 'Charles Laughton', 'Slim draaie.', 'Ou Speurverhale (Agatha Christie-styl)', 12, 4),
('And Then There Were None', 'Misterie', 'Barry Fitzgerald', 'Spanning sonder geweld.', 'Ou Speurverhale (Agatha Christie-styl)', 12, 5),
('The Mirror Crack''d', 'Misterie', 'Angela Lansbury', 'Dorpsgeheime.', 'Ou Speurverhale (Agatha Christie-styl)', 12, 6),
('Gosford Park', 'Misterie / Drama', 'Maggie Smith', 'Landgoed en intriges.', 'Ou Speurverhale (Agatha Christie-styl)', 12, 7),
('The Lady Vanishes', 'Misterie', 'Margaret Lockwood', 'Klassieke Britse spanning.', 'Ou Speurverhale (Agatha Christie-styl)', 12, 8),
('Rebecca', 'Misterie / Drama', 'Joan Fontaine', 'Atmosfeer en geheimenisse.', 'Ou Speurverhale (Agatha Christie-styl)', 12, 9),
('Dial M for Murder', 'Misterie', 'Grace Kelly', 'Slim plot.', 'Ou Speurverhale (Agatha Christie-styl)', 12, 10),
('The 39 Steps', 'Avontuur / Misterie', 'Robert Donat', 'Ou-skool spanning.', 'Ou Speurverhale (Agatha Christie-styl)', 12, 11),
('Vertigo', 'Misterie', 'James Stewart', 'Psigologies en stadig.', 'Ou Speurverhale (Agatha Christie-styl)', 12, 12),
('Rear Window', 'Misterie', 'James Stewart, Grace Kelly', 'Spanning sonder skrik.', 'Ou Speurverhale (Agatha Christie-styl)', 12, 13),
('Chinatown', 'Misterie', 'Jack Nicholson', 'Donker, slim ondersoek.', 'Ou Speurverhale (Agatha Christie-styl)', 12, 14),
('The Maltese Falcon', 'Misterie', 'Humphrey Bogart', 'Film noir-klassiek.', 'Ou Speurverhale (Agatha Christie-styl)', 12, 15),
('Laura', 'Misterie', 'Gene Tierney', 'Stylvolle raaisel.', 'Ou Speurverhale (Agatha Christie-styl)', 12, 16),
('The Big Sleep', 'Misterie', 'Humphrey Bogart, Lauren Bacall', 'Hardgekookte speurwerk.', 'Ou Speurverhale (Agatha Christie-styl)', 12, 17),
('Knives Out', 'Moderne Misterie', 'Daniel Craig', 'Christie-gees, moderne styl.', 'Ou Speurverhale (Agatha Christie-styl)', 12, 18),
('A Haunting in Venice', 'Misterie', 'Kenneth Branagh', 'Poirot met atmosfeer.', 'Ou Speurverhale (Agatha Christie-styl)', 12, 19),
('See How They Run', 'Misterie / Komedie', 'Sam Rockwell', 'Lig en slim speurverhaal.', 'Ou Speurverhale (Agatha Christie-styl)', 12, 20);
